#!/bin/bash
PROTO_GENDIR="target/generated/protobuf"
PROTO_CMD_JAVA="/usr/local/distcache-dev/bin/protoc --java_out=./target/generated/protobuf"
PROTO_LIST=$(find ./proto -name "*.proto")

mkdir -p $PROTO_GENDIR
for PRO in $PROTO_LIST
do
  echo "Generating $PRO "
  $PROTO_CMD_JAVA $PRO
  if [ $? -ne 0 ]
	then
		exit 1
	fi
done

exit 0
