// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MenuTripodData.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace xce {
namespace menutripod {

namespace {

const ::google::protobuf::Descriptor* MenuData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MenuData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MenuTripodData_2eproto() {
  protobuf_AddDesc_MenuTripodData_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MenuTripodData.proto");
  GOOGLE_CHECK(file != NULL);
  MenuData_descriptor_ = file->message_type(0);
  static const int MenuData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MenuData, userid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MenuData, cachetype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MenuData, appids_),
  };
  MenuData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MenuData_descriptor_,
      MenuData::default_instance_,
      MenuData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MenuData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MenuData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MenuData));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MenuTripodData_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MenuData_descriptor_, &MenuData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MenuTripodData_2eproto() {
  delete MenuData::default_instance_;
  delete MenuData_reflection_;
}

void protobuf_AddDesc_MenuTripodData_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024MenuTripodData.proto\022\016xce.menutripod\"="
    "\n\010MenuData\022\016\n\006userId\030\001 \002(\005\022\021\n\tcacheType\030"
    "\002 \002(\005\022\016\n\006appIds\030\003 \003(\005", 101);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MenuTripodData.proto", &protobuf_RegisterTypes);
  MenuData::default_instance_ = new MenuData();
  MenuData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MenuTripodData_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MenuTripodData_2eproto {
  StaticDescriptorInitializer_MenuTripodData_2eproto() {
    protobuf_AddDesc_MenuTripodData_2eproto();
  }
} static_descriptor_initializer_MenuTripodData_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MenuData::kUserIdFieldNumber;
const int MenuData::kCacheTypeFieldNumber;
const int MenuData::kAppIdsFieldNumber;
#endif  // !_MSC_VER

MenuData::MenuData()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MenuData::InitAsDefaultInstance() {
}

MenuData::MenuData(const MenuData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MenuData::SharedCtor() {
  _cached_size_ = 0;
  userid_ = 0;
  cachetype_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MenuData::~MenuData() {
  SharedDtor();
}

void MenuData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MenuData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MenuData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MenuData_descriptor_;
}

const MenuData& MenuData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MenuTripodData_2eproto();  return *default_instance_;
}

MenuData* MenuData::default_instance_ = NULL;

MenuData* MenuData::New() const {
  return new MenuData;
}

void MenuData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    userid_ = 0;
    cachetype_ = 0;
  }
  appids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MenuData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 userId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &userid_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_cacheType;
        break;
      }
      
      // required int32 cacheType = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cacheType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cachetype_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_appIds;
        break;
      }
      
      // repeated int32 appIds = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_appIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24, input, this->mutable_appids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_appids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_appIds;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MenuData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 userId = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->userid(), output);
  }
  
  // required int32 cacheType = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->cachetype(), output);
  }
  
  // repeated int32 appIds = 3;
  for (int i = 0; i < this->appids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->appids(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MenuData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 userId = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->userid(), target);
  }
  
  // required int32 cacheType = 2;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->cachetype(), target);
  }
  
  // repeated int32 appIds = 3;
  for (int i = 0; i < this->appids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(3, this->appids(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MenuData::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 userId = 1;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->userid());
    }
    
    // required int32 cacheType = 2;
    if (has_cachetype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cachetype());
    }
    
  }
  // repeated int32 appIds = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->appids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->appids(i));
    }
    total_size += 1 * this->appids_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MenuData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MenuData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MenuData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MenuData::MergeFrom(const MenuData& from) {
  GOOGLE_CHECK_NE(&from, this);
  appids_.MergeFrom(from.appids_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_userid(from.userid());
    }
    if (from._has_bit(1)) {
      set_cachetype(from.cachetype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MenuData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MenuData::CopyFrom(const MenuData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MenuData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void MenuData::Swap(MenuData* other) {
  if (other != this) {
    std::swap(userid_, other->userid_);
    std::swap(cachetype_, other->cachetype_);
    appids_.Swap(&other->appids_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MenuData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MenuData_descriptor_;
  metadata.reflection = MenuData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace menutripod
}  // namespace xce

// @@protoc_insertion_point(global_scope)
