// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MenuTripodData.proto

#ifndef PROTOBUF_MenuTripodData_2eproto__INCLUDED
#define PROTOBUF_MenuTripodData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace xce {
namespace menutripod {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MenuTripodData_2eproto();
void protobuf_AssignDesc_MenuTripodData_2eproto();
void protobuf_ShutdownFile_MenuTripodData_2eproto();

class MenuData;

// ===================================================================

class MenuData : public ::google::protobuf::Message {
 public:
  MenuData();
  virtual ~MenuData();
  
  MenuData(const MenuData& from);
  
  inline MenuData& operator=(const MenuData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MenuData& default_instance();
  
  void Swap(MenuData* other);
  
  // implements Message ----------------------------------------------
  
  MenuData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MenuData& from);
  void MergeFrom(const MenuData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 userId = 1;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);
  
  // required int32 cacheType = 2;
  inline bool has_cachetype() const;
  inline void clear_cachetype();
  static const int kCacheTypeFieldNumber = 2;
  inline ::google::protobuf::int32 cachetype() const;
  inline void set_cachetype(::google::protobuf::int32 value);
  
  // repeated int32 appIds = 3;
  inline int appids_size() const;
  inline void clear_appids();
  static const int kAppIdsFieldNumber = 3;
  inline ::google::protobuf::int32 appids(int index) const;
  inline void set_appids(int index, ::google::protobuf::int32 value);
  inline void add_appids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      appids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_appids();
  
  // @@protoc_insertion_point(class_scope:xce.menutripod.MenuData)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 userid_;
  ::google::protobuf::int32 cachetype_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > appids_;
  friend void  protobuf_AddDesc_MenuTripodData_2eproto();
  friend void protobuf_AssignDesc_MenuTripodData_2eproto();
  friend void protobuf_ShutdownFile_MenuTripodData_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static MenuData* default_instance_;
};
// ===================================================================


// ===================================================================

// MenuData

// required int32 userId = 1;
inline bool MenuData::has_userid() const {
  return _has_bit(0);
}
inline void MenuData::clear_userid() {
  userid_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 MenuData::userid() const {
  return userid_;
}
inline void MenuData::set_userid(::google::protobuf::int32 value) {
  _set_bit(0);
  userid_ = value;
}

// required int32 cacheType = 2;
inline bool MenuData::has_cachetype() const {
  return _has_bit(1);
}
inline void MenuData::clear_cachetype() {
  cachetype_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 MenuData::cachetype() const {
  return cachetype_;
}
inline void MenuData::set_cachetype(::google::protobuf::int32 value) {
  _set_bit(1);
  cachetype_ = value;
}

// repeated int32 appIds = 3;
inline int MenuData::appids_size() const {
  return appids_.size();
}
inline void MenuData::clear_appids() {
  appids_.Clear();
}
inline ::google::protobuf::int32 MenuData::appids(int index) const {
  return appids_.Get(index);
}
inline void MenuData::set_appids(int index, ::google::protobuf::int32 value) {
  appids_.Set(index, value);
}
inline void MenuData::add_appids(::google::protobuf::int32 value) {
  appids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MenuData::appids() const {
  return appids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MenuData::mutable_appids() {
  return &appids_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace menutripod
}  // namespace xce

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MenuTripodData_2eproto__INCLUDED
